# Generated by Django 3.0.7 on 2020-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
